// VUE/vueDemo/vue_demo/src_router_passing_props/views/Message.vue
<template>
  <div>
    <ul>
      <li v-for="message in messages" :key="message.id">
        <router-link :to="`/home/message/detail/${message.id}`">{{
          message.title
        }}</router-link>
      </li>
    </ul>
    <hr>
    <router-view></router-view>
  </div>
</template>
<script>
export default {
  data() {
    return {
      messages: [],
    };
  },
  mounted() {
    //模拟ajax请求从后台获取数据
    setTimeout(() => {
      const messages = [
        {
          id: 1,
          title: "message01",
        },
        {
          id: 2,
          title: "message02",
        },
        {
          id: 3,
          title: "message03",
        },
        {
          id: 4,
          title: "message04",
        },
      ];
      this.messages = messages;
    }, 1000);
  },
};
</script>
<style>
</style>

// ReactStudy/React-cli/hello-react/11_src_router_search/pages/Home/Message/index.jsx
import React, { Component } from "react";
import { Link,Route } from "react-router-dom";
import Detail from './Detail';

export default class Message extends Component {
    state={
        messageArr:[
            {id:'01',title:'消息1'},
            {id:'02',title:'消息2'},
            {id:'03',title:'消息3'}
        ]
    }
  render() {
      const {messageArr} = this.state
    return (

        <div>
          <ul>
           {messageArr.map((msg)=>{
               return(
                   <li key={msg.id}>
                       <Link to={`/home/message/detail/?id=${msg.id}&title=${msg.title}`}>{msg.title}</Link>
                   </li>
               )
           })}
          </ul>
          <Route path="/home/message/detail" component={Detail}/>
        </div>
    
    );
  }
}
