// VUE/vueDemo/vue_demo/src_router_programmatic_navigation/views/Message.vue
<template>
  <div>
    <ul>
      <li v-for="message in messages" :key="message.id">
        <router-link :to="`/home/message/detail/${message.id}`">{{
          message.title
        }}</router-link>
        <button class="btn btn-primary btn-xs" @click="pushPage(message.id)">push</button>
        <button class="btn btn-primary btn-xs" @click="replacePage(message.id)">replace</button>
      </li>
    </ul>
    <!-- <button class="btn btn-primary btn-xs" @click="$router.back()">回退</button> -->
    <hr>
    <router-view></router-view>
  </div>
</template>
<script>
export default {
  data() {
    return {
      messages: [],
    };
  },
  mounted() {
    //模拟ajax请求从后台获取数据
    setTimeout(() => {
      const messages = [
        {
          id: 1,
          title: "message01",
        },
        {
          id: 2,
          title: "message02",
        },
        {
          id: 3,
          title: "message03",
        },
        {
          id: 4,
          title: "message04",
        },
      ];
      this.messages = messages;
    }, 1000);
  },
  methods: {
    pushPage(id){
      this.$router.push(`/home/message/detail/${id}`)
    },
    replacePage(id){
      this.$router.replace(`/home/message/detail/${id}`)
    }
  },
};
</script>
<style>
</style>

// ReactStudy/React-cli/hello-react/13_src_Programmatic_routing/pages/Home/Message/index.jsx
import React, { Component } from "react";
import { Link, Route } from "react-router-dom";
import Detail from "./Detail";

export default class Message extends Component {
  state = {
    messageArr: [
      { id: "01", title: "消息1" },
      { id: "02", title: "消息2" },
      { id: "03", title: "消息3" },
    ],
  };

  replaceShow = (id, title) => {
    this.props.history.replace({
      pathname: "/home/message/detail",
      state: { id, title },
    });
  };
  pushShow = (id, title) => {
    this.props.history.push({
      pathname: "/home/message/detail",
      state: { id, title },
    });
  };
  back = ()=>{
    this.props.history.goBack()
  }
  forward = ()=>{
    this.props.history.goForward()
  }
  go=()=>{
    this.props.history.go(-2)
  }
  render() {
    const { messageArr } = this.state;
    return (
      <div>
        <ul>
          {messageArr.map((msg) => {
            return (
              <li key={msg.id}>
                <Link
                  replace={true}
                  to={{
                    pathname: "/home/message/detail",
                    state: { id: msg.id, title: msg.title },
                  }}
                >
                  {msg.title}
                </Link>
                &nbsp;<button onClick={()=>this.pushShow(msg.id,msg.title)}>push查看</button>
                &nbsp;
                <button onClick={() => this.replaceShow(msg.id, msg.title)}>
                  replace查看
                </button>
              </li>
            );
          })}
        </ul>
        <Route path="/home/message/detail" component={Detail} />
        <button onClick={this.back}>回退</button>&nbsp;
        <button onClick={this.forward}>前进</button>&nbsp;
        <button onClick={this.go}>Go</button>
      </div>
    );
  }
}
