// ReactStudy/React-cli/hello-react/06_src_github_fetch_demo/components/Search/Search.jsx
import React, { Component } from "react";
import PubSub from 'pubsub-js'

export default class Search extends Component {
  search = async() => {
    const {
      keyWordElement: { value: keyword },
    } = this;
    PubSub.publish('chris',{isFirst:false,isLoading:true})
    try {
      const response = await fetch(`/search/users?q=${keyword}`)
      const data = await response.json()
      PubSub.publish('chris',{isLoading:false,users:data.items})
    } catch (error) {
      console.log(error);
    }
  };

  render() {
    return (
      <section className="jumbotron">
        <h3 className="jumbotron-heading">Search Github Users</h3>
        <div>
          <input
            ref={(c) => (this.keyWordElement = c)}
            type="text"
            placeholder="enter the name you search"
          />
          &nbsp;
          <button onClick={this.search}>Search</button>
        </div>
      </section>
    );
  }
}

// VUE/vueDemo/vue_demo/src_users/components/Search.vue
<template>
   <section class="jumbotron">
      <h3 class="jumbotron-heading">Search Github Users</h3>
      <div>
        <input type="text" placeholder="enter the name you search" v-model="searchName"/>
        <button @click="search">Search</button>
      </div>
    </section>
</template>
<script>
import PubSub from 'pubsub-js';
export default {
    data() {
        return {
            searchName:''
        }
    },
    methods: {
        search(){
            const searchName = this.searchName.trim()
            if(searchName){
                PubSub.publish('search',searchName)
            }
        }
    },
}
</script>
<style>
    
</style>
